jobs:
  build: 
    executor: my-executor
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # Run a step to setup an environment variable
      # Redirect MY_ENV_VAR into $BASH_ENV
      - run: 
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "Print an SFDX_JWT_KEY var stored in a Context "
          command: echo ${SFDX_JWT_KEY}

  install_authenticate:
      environment:
    # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
    # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
    DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-v5.7.6-d42cf65-linux-amd64.tar.xz
    SFDX_DISABLE_ENCRYPTION: true
    
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: boroznaekaterina@curiospanda.com
          jwtKey: SFDX_JWT_KEY
          defaultdevhubusername: boroznaekaterina@curiospanda.com
      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it

            sfdx force:auth:list
          name: Run your SFDX commands here
orbs:
  sfdx: circleci/salesforce-sfdx@2.1.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - build:
          context: DevHub
      - install_authenticate

executors:
  my-executor:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: circleci/node:10.0-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          